id: PC8BC841D
initial_creation_type: input
source_metadata:
  title: Patrul Rinpoche Series
  language: fr
  description: 'Texts by and about the great Rimé master, Dza Patrul Orgyen Jigme
    Chökyi Wangpo (rdza dpal sprul o rgyan ''jigs med chos kyi dbang po, 1808–1887):'
  volume:
    adb7d3cb94854a3d91595c64bfdb5480:
      title: Advice for Alak Dongak
      parent: Advice
    a92edb5f9eb848de84bf7f1e27c23584:
      title: Advice to Lama Rigdzin Gyatso on Understanding the Influence of Companions
        and Avoiding and Adopting Them Accordingly
      parent: Advice
    23dd3200a68c4dcc93a6259afbae9e9a:
      title: Nine Considerations and Criteria for Benefiting Beings
      parent: Advice
    dace1a8dde1540ea8c45d6d094208b9e:
      title: The Precious Treasury of Written Instruction Transmitted One-to-One
      parent: Advice
    d8c2b43401f5479799987f5a1468cbb4:
      title: Yearning for Mountain Solitude
      parent: Advice
    2bae7dcb2a0d493cb7fa8706ea2b67c9:
      title: Aspiration to Generate Bodhicitta, Utterly Pure and Supreme
      parent: Aspiration Prayers
    78d9c1418d9c459da093117962ff80dd:
      title: Biography of Patrul Rinpoche
      parent: Biography
    f61816db0e68428e809da44488840143:
      title: Prayer to the Lineage of the Bodhicaryāvatāra
      parent: Bodhicaryāvatāra
    e584681d5d3a4f1398e74a9d2af75b3e:
      title: 'The Brightly Shining Sun: A Step-by-Step Guide to Meditating on the
        Bodhicaryāvatāra'
      parent: Bodhicaryāvatāra
    aff6ee2bee824cc196a07f1bcfd04f9f:
      title: A Brief Guide to the Stages and Paths of the Bodhisattvas
      parent: Buddhist Philosophy & Teachings
    0d15b8cce71546439f65a024fd171997:
      title: A Brief Introduction to the Bardos
      parent: Buddhist Philosophy & Teachings
    c27ad5b7d45f494c9276cc456f69d286:
      title: An Essential Instruction on Refuge and Bodhichitta
      parent: Buddhist Philosophy & Teachings
    bd534d8a79694d578d3db8b3456f20e2:
      title: An Instruction on the View of the Mahāyāna – Clarifying the Two Truths
      parent: Buddhist Philosophy & Teachings
    b1ebdcfef14b4745bda27cfcece1e72e:
      title: Preliminary Points to be Explained When Teaching the Buddha's Word or
        the Treatises
      parent: Buddhist Philosophy & Teachings
    bd34862f67714652a421d4cd62000768:
      title: 'The Concentrated Seed: How to Distinguish the Tenets of Non-Buddhist
        and Buddhist Schools'
      parent: Buddhist Philosophy & Teachings
    a0e4e0f996f94957a4b95a5a9fd16fd1:
      title: Advice on How to Put the Meaning of the Natural Great Perfection into
        Practice
      parent: Dzogchen
    e599dfb3951e42ce839004b4dc4092d8:
      title: 'Self-Liberating Meditation: A Profound Method for Attaining Enlightenment
        according to the Ultimate Great Perfection'
      parent: Dzogchen
    126bb17bd54b42a798ea4ec4f740b3bd:
      title: Brief Guide to the Stages of Visualization for the Ngöndro Practice
      parent: Ngöndro
    6702d5db1a8749b8a671b1beecb9b1a3:
      title: 'A Garland of Fresh Utpala Flowers: A Brief Synopsis of the Treasury
        of Precious Qualities, A Treatise of Pith Instructions'
      parent: Pedagogy
    0d0172ae055b42309d814fe34a841ba5:
      title: 'Mirror of the Mind: Prologue to The Treasury of Precious Qualities'
      parent: Pedagogy
    7c6fd5fa5acc4f9390aeddd9ed350553:
      title: In Praise of Glorious Vajrasattva
      parent: Praise
    455267aba0944284a3f7a07e603ef8e9:
      title: In Praise of Patrul Orgyen Jigme Chökyi Wangpo
      parent: Praise
    4483e9ca9e15447ba6f8432a52375606:
      title: 'Excellent Explanation from the Scriptural Tradition: A Brief Guide to
        the Stages of Meditating on the General Themes of the Ornament to the Prajñāpāramitā'
      parent: Prajñāpāramitā
    daff7a0ee7da4876b9b2e1e47e7e719b:
      title: 'Nectar of Lunar Crystal: A Prayer to Orgyen Chökyi Wangpo'
      parent: Prayers
    2c84a316fa0e4f9287ec7b724fa9d992:
      title: Prayer to Chökyi Wangpo, the Bodhisattva and Tamer of Beings
      parent: Prayers
    203d264b71f6469082ee2abe8a589e96:
      title: Prayer to Machik Labdrön
      parent: Prayers
    483947a43cc6457caa2d8a39f6fa81a5:
      title: Prayer to Śāntideva and Dam, Tsang and Jam of Katok
      parent: Prayers
    b2330f7b21e647fba47bf1fca7a85425:
      title: Brief Windhorse Practice of Tārā
      parent: Prayers & Practices
    54359f0183634864ad354d272ec58dbb:
      title: Temple Dedication Prayer
      parent: Prayers & Practices
    0621e4985c9547cd9177c259d3243527:
      title: A Brief Mañjuśrī Sādhana
      parent: Sādhanas
    27a9074c1a3c42f0b2f63258aad2342b:
      title: The Method for Observing the Eight-Branched One-Day Vow
      parent: Sojong
    b0ed179dc27e44eeb2be04afae0e52a6:
      title: The Special Teaching of the Wise and Glorious King – Commentary
      parent: Special Teaching of the Wise and Glorious King
    3b1b158ca2a7458eac2476e7b3d7917d:
      title: The Special Teaching of the Wise and Glorious King—Root Text
      parent: Special Teaching of the Wise and Glorious King
    9a3fc967a2be404195b2291517982d97:
      title: The Special Teaching of the Wise and Glorious King—Root Text (arranged
        in Tibetan-English verses)
      parent: Special Teaching of the Wise and Glorious King
    63b5c205539244b2b7f66cb0b586da16:
      title: A Topical Outline of the General Confession Spoken by the Five Great
        Sages
      parent: Topical Outlines
    32c4a0ea317b42f78ee7df3e6a9dc3fa:
      title: The Way to Explain the King of All Aspiration Prayers, the Secret Vajra
        Knot
      parent: Topical Outlines
    906efc47c2964cc7b3e265d494fd678b:
      title: Topical Outline of the Prayer That Swiftly Fulfils All Wishes (Sampa
        Nyur Drupma)
      parent: Topical Outlines
    c42237de9d504929a6a8d3013924747a:
      title: 'Transference: Enlightenment Without Meditation (Compilation)'
      parent: Transference (Phowa)
    441da0c6e0834c8aa2242bcd632f522c:
      title: The Ritual of the Bodhisattva Vow According to the Tradition of Patrul
        Rinpoche
      parent: Vows & Commitments
created_at: '2022-03-01T01:13:56.743952'
last_modified_at: '2022-03-01T01:13:56.743955'
